# Development/Stage/Production environment

# Base image
FROM node:22.14-alpine3.21

RUN apk add --no-cache bash

RUN npm i -g @nestjs/cli

RUN mkdir /app

WORKDIR /app

EXPOSE 3000

# Bundle app source
COPY src ./src
COPY package*.json ./
COPY tsconfig* ./

# Install app dependencies
RUN npm ci

# Creates a "dist" folder with the production build
RUN npm run build

# Optional: remove dev dependencies for smaller image
RUN npm prune --omit=dev