version: '3'
networks:
  par_net:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/16

services:
  postgres:
    build:
        context: docker/postgres
        dockerfile: Dockerfile
    networks:
      par_net:
        ipv4_address: 10.2.1.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_DB: UDK2
    ports:
      - "54322:5432"
    volumes:
    - ./docker/db:/var/lib/postgresql/data
    tty: true 

  postgres_test:
    build:
        context: docker/postgres
        dockerfile: Dockerfile
    networks:
      par_net:
        ipv4_address: 10.2.1.2
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: asdfasdf_test
      POSTGRES_DB: UDK2_test
    ports:
      - "54321:5432"
    volumes:
    - ./docker/db_test:/var/lib/postgresql/data
    tty: true     
      
  redis:
    image: redis:7.2.4
    networks:
      par_net:
        ipv4_address: 10.2.1.10
    restart: always
    ports:
      - 63792:6379
    command: redis-server
    volumes: 
      - ./docker/redis:/data

  api:
    depends_on:
      - postgres
      - redis
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - .:/app:rw
    networks:
      par_net:
        ipv4_address: 10.2.1.1
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      IS_WORKER: "false"
    ports:
      - "3001:3001"
      - "9229:9229"
    command: >
      bash -c "yarn install --frozen-lockfile
      && rm -rf dist
      && nest start --debug 0.0.0.0:9229 --watch --preserveWatchOutput"
